services:
  rest:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "septic_monitor.rest:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    volumes:
    - "./septic_monitor:/opt/sm/septic_monitor"
    - "/etc/timezone:/etc/timezone"
    environment:
      REDIS_HOST: redis
      TZ: America/Winnipeg
    restart: unless-stopped
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
    - "6379:6379"
    volumes:
    - "./redis/redis.conf:/etc/redis.conf:ro"
    - "./redis/data:/data"
    environment:
      TZ: America/Winnipeg
    restart: unless-stopped
  nginx:
    image: nginx
    volumes:
    - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    - "./web:/usr/share/nginx/html:ro"
    ports:
    - "80:80"
    environment:
      TZ: America/Winnipeg
    restart: unless-stopped
