services:
  redis:
    image: erniesprojects/sepmon_redis
    ports:
    - "127.0.0.1:6379:6379"
    volumes:
    - "./redis/redis.conf:/etc/redis.conf:ro"
    - "./redis/data:/data"
    env_file: env
    restart: unless-stopped
  rest:
    image: erniesprojects/sepmon_rest
    volumes:
    - "./septic_monitor:/opt/sm/septic_monitor"
    - "/etc/timezone:/etc/timezone"
    env_file: env
    restart: unless-stopped
    depends_on:
    - "redis"
  nginx:
    image: nginx
    volumes:
    - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    - "./web:/usr/share/nginx/html:ro"
    ports:
    - "80:80"
    env_file: env
    restart: unless-stopped
    depends_on:
    - "rest"
  pump_v:
    image: erniesprojects/sepmon_rest
    volumes:
    - "./septic_monitor:/opt/sm/septic_monitor"
    - "/etc/timezone:/etc/timezone"
    env_file: env
    restart: unless-stopped
    privileged: true
    command: ["python", "/opt/sm/septic_monitor/pump_v.py"]
    depends_on:
    - "redis"
  pump_i:
    image: erniesprojects/sepmon_rest
    volumes:
    - "./septic_monitor:/opt/sm/septic_monitor"
    - "/etc/timezone:/etc/timezone"
    env_file: env
    restart: unless-stopped
    privileged: true
    command: ["python", "/opt/sm/septic_monitor/pump_i.py"]
    depends_on:
    - "redis"
