services:
  redis:    
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
    - "6379:6379"
    volumes:
    - "./redis/redis.conf:/etc/redis.conf"
    - "./redis/sock:/sock"
    - "./redis/data:/data"
