services:
  db:
    image: "timescale/timescaledb:latest-pg12"
    env_file: .env
    ports:
    - "127.0.0.1:5432:5432"
    volumes:
    - "pgdata:/var/lib/postgresql/data"
    restart: unless-stopped
  rest:
    image: erniesprojects/sepmon_base
    command: ["uvicorn", "septic_monitor.rest:app", "--host", "0.0.0.0", "--port", "80"]    
    env_file: .env    
    volumes:
    - "./septic_monitor:/opt/sm/septic_monitor"
    - "/etc/timezone:/etc/timezone"
    restart: unless-stopped
    depends_on:
    - "db"
  nginx:
    image: nginx
    env_file: .env    
    volumes:
    - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    - "./web:/usr/share/nginx/html:ro"
    ports:
    - "80:80"
    restart: unless-stopped
    depends_on:
    - "rest"
  pump_v:
    image: erniesprojects/sepmon_base
    env_file: .env    
    volumes:
    - "./septic_monitor:/opt/sm/septic_monitor"
    - "/etc/timezone:/etc/timezone"
    restart: unless-stopped
    privileged: true
    command: ["python", "/opt/sm/septic_monitor/pump_v.py"]
    depends_on:
    - "db"
  

volumes:
  pgdata:
