services:
  redis:    
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
    - "6379:6379"
    volumes:
    - "./redis/redis.conf:/etc/redis.conf:ro"
    - "./redis/data:/data"
  nginx:
    image: nginx
    volumes:
    - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    - "./web:/usr/share/nginx/html:ro"
    ports:
    - "80:80"
