FROM redis:6

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install git build-essential libssl-dev python3-gevent python3-pip && \
    python3 -m pip install pip setuptools wheel --upgrade

WORKDIR /usr/share

RUN git clone --recursive https://github.com/RedisTimeSeries/RedisTimeSeries.git && \
    cd RedisTimeSeries && make setup && make build

WORKDIR /data

CMD ["redis-server", "/etc/redis.conf"]
