on: [push]

jobs:
  redis_docker_image:
    runs-on: ubuntu-latest
    name: Builds redis docker image
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build -f Dockerfile.redis .
